"""added default avatar url to user model

Revision ID: 83247907649b
Revises: 658e7426e007
Create Date: 2021-10-14 14:21:23.559704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83247907649b'
down_revision = '658e7426e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
