"""added Image class, and added relationships between images and users for the third time

Revision ID: 52695b63ee14
Revises: ffdc0a98111c
Create Date: 2021-10-10 13:05:33.198085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52695b63ee14'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.String(
                        length=255), nullable=False),
                    sa.Column('caption', sa.Text(), nullable=True),
                    sa.Column('likes_count', sa.Integer(), nullable=False),
                    sa.Column('comments_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
