"""adding default avatar url to user model

Revision ID: 658e7426e007
Revises: 80005b95f103
Create Date: 2021-10-14 14:20:17.323829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658e7426e007'
down_revision = '80005b95f103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
